### PR TITLE
Unified, cleaner, and improved Baggers and Locations pages

### PR DESCRIPTION
**Pull request by janosgyerik**
All the changes are in baggers.html and locations.html, hope you'll like them. You can see the result here:
http://janosgyerik.github.io/BrownBagLunch/baggers.html
http://janosgyerik.github.io/BrownBagLunch/locations.html
- Unified Foundation versions 3-4: use Foundation 4 in both
- Unified header and footer
- Pinned header to the top
- Added links to each other in the header
- Added "Baggers"/"Locations" in the page titles
- Removed colons ":" from Label elements

Note that using Foundation 4 has some unintended consequences: the fonts look bigger everywhere somehow. I hope that's ok...

If you like where this is going, let me know and I can do the same for past-bbl.html. I think it would be good to unify index.html too, but since it's not using Foundation at all (it's using bootstrap), the result will look quite different from the current page. So let me know how you want to deal with that.

Cheers,
Janos

### CODE REVIEW

**Comment by nrichand** [comment]
Thank you very much @janosgyerik this is very nice! I appreciate you take some time to help us. I totally forgot to migrate location to foundation 4. 

I would like to switch index to foundation too but there is to much work for me and my css skill are low. To begin quickly I used a template with bootstrap. I don't know if the gain is worth the effort...

Btw many thanks Janos.

**Comment by janosgyerik** [comment]
Btw I tried with Foundation 5 too, but the look & feel was very different in the callout panels, so I dropped it and went back to Foundation 4 in the end.

I think it will be nice to have a unified look & feel on the entire site. Otherwise it might seem you are not on the same site. But, actually, I really don't like coding in HTML & CSS :s 

I'll see what I can do. If converting the front page is easy enough, then I'll probably do it. If I don't send a PR within a week or so that means I gave up....

**Comment by nrichand** [comment]
;) good luck.
I will have a look to foundation 5, I miss this new release.

**Comment by janosgyerik** [comment]
Actually, do we really prefer Foundation? The (for now unused) test page http://www.brownbaglunch.fr/baggers-test.html looks very promising and it's using Bootstrap. Even though I just unified two pages for Foundation 4, I don't mind refactoring them again to use Bootstrap. In that case the front page can stay pretty much as it is. I like the test page better visually too, especially the dropdown.

What do you think?

**Comment by janosgyerik** [comment]
Hmm, I just came across this post:
http://abetteruserexperience.com/2013/08/twitter-bootstrap-3-vs-foundation-4-which-one-should-you-use/

It firmly concludes that Foundation 4 beats Bootstrap 3 _for mobile_. However:
- I could be wrong but the poster seems to have a strong bias toward Foundation
- Is mobile important for this site at all?

Well, I guess I'm ok with whichever framework you guys prefer. I have more experience with Bootstrap, so it would be considerably easier for me, but that should not be the decisive factor.

**Pull request merged**
