### PR TITLE
Ajoute cgrand comme bagger

### PR DESCRIPTION
**Pull request by cgrand**

### CODE REVIEW

**Comment by ptitfred** [comment]
Gaffe, le format vient de changer

**Comment by nrichand** [comment]
Yes, je vais la merger à la mano.

**Comment by cgrand** [comment]
Je veux bien modifier moi-même si vous me dite où regarder pour le nouveau
format.

On Thu, Dec 19, 2013 at 4:21 PM, Nathaniel Richand <notifications@github.com

> wrote:
> 
> Yes, je vais la merger à la mano.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/nrichand/BrownBagLunch/pull/135#issuecomment-30936550
> .

## 

On Clojure http://clj-me.cgrand.net/
Clojure Programming http://clojurebook.com
Training, Consulting & Contracting http://lambdanext.eu/

**Comment by nrichand** [comment]
Pas de soucis, je te le fait rapidement :)

**Comment by cgrand** [comment]
merci

On Thu, Dec 19, 2013 at 4:36 PM, Nathaniel Richand <notifications@github.com

> wrote:
> 
> Merged #135 https://github.com/nrichand/BrownBagLunch/pull/135.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/nrichand/BrownBagLunch/pull/135
> .

## 

On Clojure http://clj-me.cgrand.net/
Clojure Programming http://clojurebook.com
Training, Consulting & Contracting http://lambdanext.eu/

**Pull request merged**
