### PR TITLE
Adapt baggers page to the new model

### PR DESCRIPTION
**Pull request by dadoonet**
In https://github.com/brownbaglunch/bblfr_data/pull/66 we meant to change the model.

This PR (WIP) takes care of the change.

It will help to make progress in baby steps:
- update the model: https://github.com/brownbaglunch/bblfr_data/pull/66
- update the website to the new model: this PR
- rewrite the website using elasticsearch as the search backend

Note that to test it, you need to generate `../bblfr_data/rewrite/baggers-new.js`.
Then uncomment the `local` part and comment the `remote` part.

I found with this commit BTW that some cities are missing. I'll come with another PR to fix that...

```
city not found Vesoul
city not found Besançon
city not found Belfort
city not found Mulhouse
city not found Nancy
```

### CODE REVIEW

**Comment by dadoonet** [comment]
I merged and ran again this PR.

Note that we will need to cleanup some data:

```
city not found Vesoul
city not found Besançon
city not found Belfort
city not found Mulhouse
city not found Nancy
city not found Orléans
GET file://avatars.borisschapira.com/boris_1light_300_fuchsia.jpg net::ERR_FILE_NOT_FOUND
GET http://media.licdn.com/mpr/mpr/shrink_200_200/p/1/000/2b7/1f9/259b373.jpg 404 (Not Found)
GET https://fbcdn-profile-a.akamaihd.net/hprofile-ak-xfa1/v/t1.0-1/c0.0.320.320…d42dfa9348&oe=54E99E54&__gda__=1425364962_ff9796691bbf73f194716cf5924b2d57 403 ()
GET https://media.licdn.com/media/p/8/000/1e1/205/29f40de.jpg 404 ()
GET http://fr.gravatar.com/userimage/8198086/417f6125a7549374926e4935f9272ad6.jpg?size=500 404 (Not Found)
GET http://cltdl.fr/profile_square.jpg 404 (Not Found)
GET http://m.c.lnkd.licdn.com/media/p/4/000/15f/25a/14e30e7.jpg 404 (Not Found)
GET http://www.loxodata.com/loxodata.v2/images/sas_277.jpg 404 (Not Found)
GET https://pbs.twimg.com/profile_images/2284064030/r1fue8rqkl904pvija46.jpeg 404 (Not Found)
GET http://m.c.lnkd.licdn.com/mpr/mpr/shrink_200_200/p/1/000/1a1/3d1/258cb42.jpg 404 (Not Found)
GET http://www.timwi.com/img/team/cbegot.png 404 (Not Found)
GET https://pbs.twimg.com/profile_images/2776155908/7a1460aa6728eda8e4a2ca56f425ac99.jpeg 404 (Not Found)
GET https://pbs.twimg.com/profile_images/3538863249/7c6adb61a6b0554c019b2a26711c7afd_400x400.jpeg 404 (Not Found)
GET https://pbs.twimg.com/profile_images/1749868293/id-1_small.png 404 (Not Found)
Google Maps API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys
Google Maps API warning: SensorNotRequired https://developers.google.com/maps/documentation/javascript/error-messages#sensor-not-required
```

**Comment by dadoonet** [comment]
City issues is now solved with this commit: https://github.com/brownbaglunch/bblfr_data/commit/100a394a963d61bd2bdb141623360e4894a616dd

**Comment by dadoonet** [comment]
My local version version is now working well.

As I'd like to move this project forward, I'll most likely merge this unless anyone objects.
Obviously, I'll commit first the new version of the baggers JSON...

**Comment by Nilhcem** [comment]
- You renamed the `baggers` array to a `speakers` array.
  For consistency, I would have modified the associated endpoint too: from `baggers.js` to `speakers.js`. Yet, optional as this same page also serves a "cities" array.
  BTW I found this new cities field structure unnecessarily complicated to parse, compared to the previous format.
- The Human Resources model (`baggers-rh.js`) is not updated yet to the new format
- All arrays in the speakers model are plurals (sessions, cities, tags, websites).
  For consistency, new `contact` field should be plural too (-> `contacts`).
  This should also ideally apply to `lang` (yet we could believe lang is a short form for `languages`)

**Comment by dadoonet** [comment]
I do agree. Wanna open a new issue or a PR ?

**Comment by Nilhcem** [comment]
Sure, I'll try to send some PRs later this week

**Pull request merged**
