### PR TITLE
Update HR site to the new json structure

### PR DESCRIPTION
**Pull request by Nilhcem**
**Note: This PR depends on https://github.com/brownbaglunch/bblfr_data/pull/125**

 It must be merged just after merging https://github.com/brownbaglunch/bblfr_data/pull/125

This commit is mostly a merge with the bbl website that already uses the new `baggers.js` json structure

### CODE REVIEW

**Review by dadoonet — APPROVED** [review]
I gave a quick look at it. It looks good to me. I guess you tested that locally and that it was working for you?

**Comment by Nilhcem** [comment]
yep

**Comment by dadoonet** [comment]
Well done! Site is now live with the new format. http://www.brownbaglunch.fr/rh/baggers.html

Thanks!

**Comment by Nilhcem** [comment]
:+1:

**Pull request merged**
