### PR TITLE
Technical changes on locations page to fix http://validator.w3.org/ validation errors

### PR DESCRIPTION
**Pull request by janosgyerik**

### CODE REVIEW

**Comment by nrichand** [comment]
Thanks sir!

**Comment by nrichand** [comment]
Hey @janosgyerik, when will you join us as a bagger? ;)

**Comment by janosgyerik** [comment]
You're welcome! Maybe next year, I can give it a try!

**Comment by nrichand** [comment]
Good, I hope you will join us. I feel that you have a lot of interesting things to share :)

**Pull request merged**
